language: python

install:
  - pip install pybind11  # to avoid issues with george
  - pip install -r requirements.txt
  #- conda config --add channels conda-forge
  #- conda install -c conda-forge numpy matplotlib pandas lmfit peakutils george emcee extinction sfdmap

script:
  - nosetests
