language: python

install:
  - pip install pybind11  # to avoid issues with george
  - pip install -U -r requirements.txt
  - python setup.py develop

  # Anaconda version - [NOT FULLY TESTED]
  # Install the latest version of Miniconda
  #- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- source "$HOME/miniconda/etc/profile.d/conda.sh"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  # Useful for debugging any issues with conda
  #- conda info -a

  # Install packages
  #- conda config --add channels conda-forge
  #- conda create -n test_pisco python=$TRAVIS_PYTHON_VERSION numpy matplotlib pandas lmfit peakutils george emcee extinction sfdmap astropy pytest
  #- source activate test_pisco
  #- python setup.py develop

script:
  - pytest
